"""Added account table

Revision ID: 0897487021e9
Revises: 575ac416b522
Create Date: 2023-04-18 08:34:51.914813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0897487021e9'
down_revision = '575ac416b522'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('location', sa.String(), nullable=True))
    op.drop_column('participants', 'registry_from')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('registry_from', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('participants', 'location')
    # ### end Alembic commands ###
