"""Added account table

Revision ID: 2cd32abd2f42
Revises: 775bf4a71d08
Create Date: 2023-04-03 10:02:14.377784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cd32abd2f42'
down_revision = '775bf4a71d08'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('attend_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants', 'attend_by')
    # ### end Alembic commands ###
