"""Added account table

Revision ID: 4f127fbd8be4
Revises: 9f78b03a6491
Create Date: 2023-04-18 11:01:39.030780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f127fbd8be4'
down_revision = '9f78b03a6491'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
