"""Added account table

Revision ID: 575ac416b522
Revises: 83138fe67eb1
Create Date: 2023-04-08 13:52:54.637830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '575ac416b522'
down_revision = '83138fe67eb1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('events_participantId_fkey', 'events', type_='foreignkey')
    op.drop_column('events', 'participantId')
    op.add_column('participants', sa.Column('event_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'participants', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'participants', type_='foreignkey')
    op.drop_column('participants', 'event_id')
    op.add_column('events', sa.Column('participantId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('events_participantId_fkey', 'events', 'participants', ['participantId'], ['id'])
    # ### end Alembic commands ###
