"""Added account table

Revision ID: 775bf4a71d08
Revises: 0aa608456abb
Create Date: 2023-04-03 09:14:07.119757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '775bf4a71d08'
down_revision = '0aa608456abb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('registration_time', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants', 'registration_time')
    # ### end Alembic commands ###
