"""Added account table

Revision ID: 83138fe67eb1
Revises: b4ce034a3618
Create Date: 2023-04-03 14:47:22.041702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83138fe67eb1'
down_revision = 'b4ce034a3618'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
