"""Added account table

Revision ID: 9f78b03a6491
Revises: 0897487021e9
Create Date: 2023-04-18 10:54:29.766358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f78b03a6491'
down_revision = '0897487021e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
