"""Added account table

Revision ID: b4ce034a3618
Revises: 2cd32abd2f42
Create Date: 2023-04-03 14:27:32.739465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4ce034a3618'
down_revision = '2cd32abd2f42'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants', 'status')
    # ### end Alembic commands ###
